# Generated by Django 5.2.8 on 2025-11-17 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='পদের নাম')),
                ('company_name', models.CharField(default='আঙ্গারিয়া ক্ষুদ্র ব্যবসায়ী ও সমবায় সমিতি লিঃ', max_length=200, verbose_name='প্রতিষ্ঠানের নাম')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='job_logos/', verbose_name='প্রতিষ্ঠানের লোগো')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='কাজের স্থান')),
                ('experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='অভিজ্ঞতা (যেমন: ৪ থেকে ৫ বছর)')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='সংক্ষিপ্ত বিবরণ (তালিকা পেজের জন্য)')),
                ('description', models.TextField(verbose_name='চাকরির বিস্তারিত বিবরণ')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='আবেদনের শেষ তারিখ')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='প্রকাশের তারিখ')),
            ],
            options={
                'verbose_name': 'চাকরির পোস্ট',
                'verbose_name_plural': 'চাকরির পোস্টসমূহ',
                'ordering': ['application_deadline'],
            },
        ),
    ]
