# Generated by Django 5.2.8 on 2025-11-17 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="For internal reference (e.g., 'Spring Sale Ad')", max_length=100)),
                ('image', models.ImageField(upload_to='ads/', verbose_name='Ad Image')),
                ('link', models.URLField(blank=True, help_text='Optional: URL the ad clicks to', max_length=255, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ad Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Ad End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Manually turn this ad on or off')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['start_date'],
            },
        ),
    ]
