# Generated by Django 5.2.8 on 2025-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পণ্য নাম')),
                ('image', models.ImageField(upload_to='products/', verbose_name='ছবি')),
                ('price', models.IntegerField(verbose_name='বর্তমান মূল্য')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='পূর্বের মূল্য (অপশনাল)')),
                ('description', models.TextField(verbose_name='বিবরণ')),
            ],
        ),
    ]
