# Generated by Django 5.2.8 on 2025-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/', verbose_name='হিরো ছবি')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='ক্যাপশন (অপশনাল)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'হিরো ছবি',
                'verbose_name_plural': 'হিরো ছবিসমূহ',
            },
        ),
    ]
