# Generated by Django 5.2.8 on 2025-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ব্রাঞ্চের নাম')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='ঠিকানা (অপশনাল)')),
                ('latitude', models.FloatField(verbose_name='Latitude (অক্ষাংশ)')),
                ('longitude', models.FloatField(verbose_name='Longitude (দ্রাঘিমাংশ)')),
            ],
            options={
                'verbose_name': 'Branch Location',
                'verbose_name_plural': 'Branch Locations',
            },
        ),
    ]
