# Generated by Django 5.2.8 on 2025-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='আমাদের শাখার অবস্থান', max_length=200, verbose_name='সেকশন শিরোনাম')),
                ('description', models.TextField(verbose_name='ছোট বিবরণ')),
                ('office_address', models.CharField(max_length=300, verbose_name='প্রধান কার্যালয়')),
                ('phone_numbers', models.TextField(verbose_name='ফোন নম্বর (প্রতি লাইনে একটি)')),
                ('emails', models.TextField(verbose_name='ইমেইল (প্রতি লাইনে একটি)')),
            ],
            options={
                'verbose_name': 'Contact Info Setup',
                'verbose_name_plural': 'Contact Info Setup',
            },
        ),
    ]
