# Generated by Django 5.2.8 on 2025-11-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsettings',
            options={'verbose_name': 'Contact Info (Simple)', 'verbose_name_plural': 'Contact Info (Simple)'},
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='section_title',
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='content',
            field=models.TextField(default='', verbose_name='বিস্তারিত তথ্য (ঠিকানা, ফোন, ইত্যাদি)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='title',
            field=models.CharField(default='আমাদের শাখার অবস্থান', max_length=200, verbose_name='হেডার / শিরোনাম'),
        ),
    ]
